import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

type Severity = "INFO" | "WATCH" | "ALERT" | "CRITICAL";
type NewsItem = { title: string; source: string; url: string; category: string; severity: Severity; publishedAt: string };
type Market = { symbol: string; name: string; price: number | null; changePercent: number | null; source: string; status: string };
type EventItem = { title: string; source: string; url: string; category: string; severity: Severity; publishedAt: string; lat: number; lon: number; summary: string; impact: string };

const watch = ["SPY","QQQ","AAPL","MSFT","NVDA","TSLA"];
const coords: Record<string,[number,number]> = { us:[39,-98], eu:[50,10], asia:[34,100], middleeast:[29,45], latam:[-15,-60], global:[20,0], china:[35,103], russia:[61,90], ukraine:[49,31], israel:[31,35], iran:[32,53], taiwan:[24,121] };
function key(name:string){ return process.env[name] || ""; }
function status(name:string, needsKey=true){ return needsKey && !key(name) ? "missing_key" : "configured"; }
async function getJson(url:string, init?:RequestInit){ const r=await fetch(url,{...init,next:{revalidate:300}}); if(!r.ok) throw new Error(String(r.status)); return r.json(); }
function sev(text:string):Severity{ const t=text.toLowerCase(); if(/war|missile|attack|invasion|default|crisis|earthquake|explosion/.test(t)) return "CRITICAL"; if(/sanction|lawsuit|fraud|investigation|conflict|inflation|rate/.test(t)) return "ALERT"; if(/earnings|policy|fed|oil|supply|regulation/.test(t)) return "WATCH"; return "INFO"; }
function category(text:string){ const t=text.toLowerCase(); if(/oil|gas|energy|opec/.test(t)) return "Energy"; if(/war|military|missile|conflict/.test(t)) return "Conflict"; if(/congress|federal|regulation|law|sec |filing/.test(t)) return "Government"; if(/home|housing|mortgage|real estate/.test(t)) return "Real Estate"; if(/tech|ai|semiconductor|chip/.test(t)) return "Technology"; if(/inflation|jobs|fed|rates|gdp/.test(t)) return "Economy"; if(/china|russia|iran|taiwan|israel|ukraine/.test(t)) return "Geopolitics"; return "Markets"; }
function locate(text:string):[number,number]{ const t=text.toLowerCase(); for(const [k,v] of Object.entries(coords)){ if(t.includes(k)) return v; } return coords.global; }
function market(symbol:string, price:number|null, change:number|null, source:string, status="ok"):Market{ return {symbol,name:symbol,price,changePercent:change,source,status}; }

async function alphaMarkets(statuses:Record<string,string>){ if(!key("ALPHA_VANTAGE_API_KEY")){ statuses.AlphaVantage="missing_key"; return []; } const out:Market[]=[]; for(const s of watch.slice(0,4)){ try{ const j=await getJson(`https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=${s}&apikey=${key("ALPHA_VANTAGE_API_KEY")}`); const q=j["Global Quote"]||{}; out.push(market(s, Number(q["05. price"]||NaN)||null, Number(String(q["10. change percent"]||"").replace("%","")||NaN)||null, "Alpha Vantage")); statuses.AlphaVantage="ok"; }catch{ statuses.AlphaVantage="error"; } } return out; }
async function finnhub(statuses:Record<string,string>){ if(!key("FINNHUB_API_KEY")){ statuses.Finnhub="missing_key"; return {markets:[],news:[] as NewsItem[]}; } const markets:Market[]=[]; const news:NewsItem[]=[]; try{ for(const s of watch){ const q=await getJson(`https://finnhub.io/api/v1/quote?symbol=${s}&token=${key("FINNHUB_API_KEY")}`); markets.push(market(s, q.c||null, q.dp||null, "Finnhub")); } const n=await getJson(`https://finnhub.io/api/v1/news?category=general&token=${key("FINNHUB_API_KEY")}`); for(const x of (Array.isArray(n)?n:[]).slice(0,20)){ news.push({title:x.headline,source:x.source||"Finnhub",url:x.url,category:category(x.headline),severity:sev(x.headline),publishedAt:new Date((x.datetime||0)*1000).toISOString()}); } statuses.Finnhub="ok"; }catch{ statuses.Finnhub="error"; } return {markets,news}; }
async function newsApi(statuses:Record<string,string>){ const out:NewsItem[]=[]; if(key("NEWS_API_KEY")){ try{ const j=await getJson(`https://newsapi.org/v2/top-headlines?language=en&category=business&pageSize=25&apiKey=${key("NEWS_API_KEY")}`); for(const a of j.articles||[]) out.push({title:a.title,source:a.source?.name||"NewsAPI",url:a.url,category:category(a.title),severity:sev(a.title),publishedAt:a.publishedAt}); statuses.NewsAPI="ok"; }catch{ statuses.NewsAPI="error"; } } else statuses.NewsAPI="missing_key"; if(key("WORLD_NEWS_API_KEY")){ try{ const j=await getJson(`https://api.worldnewsapi.com/search-news?text=markets%20economy%20geopolitics%20regulation&language=en&number=20`,{headers:{"x-api-key":key("WORLD_NEWS_API_KEY")}}); for(const a of j.news||[]) out.push({title:a.title,source:a.author||"World News API",url:a.url,category:category(a.title),severity:sev(a.title),publishedAt:a.publish_date}); statuses.WorldNews="ok"; }catch{ statuses.WorldNews="error"; } } else statuses.WorldNews="missing_key"; return out; }
async function gdelt(statuses:Record<string,string>){ const out:EventItem[]=[]; try{ const j=await getJson(`${process.env.GDELT_BASE_URL||"https://api.gdeltproject.org"}/api/v2/doc/doc?query=geopolitics%20OR%20sanctions%20OR%20conflict%20OR%20energy&mode=artlist&format=json&maxrecords=30`); for(const a of j.articles||[]){ const [lat,lon]=locate(`${a.title} ${a.seendate}`); out.push({title:a.title,source:a.sourceCountry||"GDELT",url:a.url,category:category(a.title),severity:sev(a.title),publishedAt:a.seendate||new Date().toISOString(),lat,lon,summary:a.title,impact:`Potential ${category(a.title).toLowerCase()} impact. Verify source details.`}); } statuses.GDELT="ok"; }catch{ statuses.GDELT="error"; } return out; }
async function coin(statuses:Record<string,string>){ try{ const j=await getJson("https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd&include_24hr_change=true"); statuses.CoinGecko="ok"; return [market("BTC",j.bitcoin?.usd??null,j.bitcoin?.usd_24h_change??null,"CoinGecko"),market("ETH",j.ethereum?.usd??null,j.ethereum?.usd_24h_change??null,"CoinGecko")]; }catch{ statuses.CoinGecko="error"; return []; } }
async function macro(statuses:Record<string,string>){ const out:Record<string,string>={}; if(key("FRED_API_KEY")){ try{ const j=await getJson(`https://api.stlouisfed.org/fred/series/observations?series_id=DGS10&api_key=${key("FRED_API_KEY")}&file_type=json&sort_order=desc&limit=1`); out["US 10Y"] = j.observations?.[0]?.value || "Unavailable"; statuses.FRED="ok"; }catch{ statuses.FRED="error"; } } else statuses.FRED="missing_key"; if(key("BLS_API_KEY")){ statuses.BLS="configured"; } else statuses.BLS="missing_key"; try{ const wb=await getJson(`${process.env.WORLD_BANK_BASE_URL||"https://api.worldbank.org/v2"}/country/US/indicator/NY.GDP.MKTP.CD?format=json&per_page=1`); out["World Bank US GDP"] = wb?.[1]?.[0]?.value ? Number(wb[1][0].value).toLocaleString() : "Unavailable"; statuses.WorldBank="ok"; }catch{ statuses.WorldBank="error"; } return out; }
async function government(statuses:Record<string,string>){ const regs:NewsItem[]=[]; const filings:NewsItem[]=[]; try{ const j=await getJson(`${process.env.FEDERAL_REGISTER_BASE_URL||"https://www.federalregister.gov/api/v1"}/documents.json?per_page=10&order=newest`); for(const d of j.results||[]) regs.push({title:d.title,source:"Federal Register",url:d.html_url,category:"Government",severity:sev(d.title),publishedAt:d.publication_date}); statuses.FederalRegister="ok"; }catch{ statuses.FederalRegister="error"; } if(key("CONGRESS_API_KEY")){ try{ const j=await getJson(`https://api.congress.gov/v3/bill?format=json&limit=10&api_key=${key("CONGRESS_API_KEY")}`); for(const b of j.bills||[]) regs.push({title:b.title,source:"Congress.gov",url:b.url,category:"Government",severity:sev(b.title),publishedAt:b.updateDate}); statuses.Congress="ok"; }catch{ statuses.Congress="error"; } } else statuses.Congress="missing_key"; try{ const ua=key("SEC_USER_AGENT")||"WorldMarketWatcher/1.0 contact@example.com"; const j=await getJson("https://data.sec.gov/submissions/CIK0000320193.json",{headers:{"user-agent":ua}}); const recent=j.filings?.recent; for(let i=0;i<Math.min(8,recent?.accessionNumber?.length||0);i++){ filings.push({title:`AAPL ${recent.form[i]} filing`,source:"SEC EDGAR",url:`https://www.sec.gov/Archives/edgar/data/320193/${String(recent.accessionNumber[i]).replace(/-/g,"")}/${recent.primaryDocument[i]}`,category:"SEC Filing",severity:"WATCH",publishedAt:recent.filingDate[i]}); } statuses.SEC="ok"; }catch{ statuses.SEC="error"; } return {regs,filings}; }
function risk(news:NewsItem[],events:EventItem[]){ const all=[...news,...events]; const score=(re:RegExp)=>Math.min(100,Math.round(all.filter(x=>re.test(`${x.title} ${x.category}`.toLowerCase())).length*12)); return {"Market Risk":score(/market|earnings|stock|rate|fed|inflation/),"Geopolitical Risk":score(/war|conflict|sanction|china|russia|iran|ukraine|israel|taiwan/),"Regulatory Risk":score(/law|regulation|congress|federal|sec|filing/),"Energy Risk":score(/oil|gas|energy|opec/),"Real Estate Risk":score(/housing|mortgage|real estate|rates/)}; }

export async function GET(){ const statuses:Record<string,string>={OpenAI:key("OPENAI_API_KEY")?"configured":"missing_key",Reddit:key("REDDIT_CLIENT_ID")?"configured":"missing_key",Binance:key("BINANCE_API_KEY")?"configured":"missing_key",Census:key("CENSUS_API_KEY")?"configured":"missing_key"}; const [av,fh,na,gd,cg,ma,gov]=await Promise.all([alphaMarkets(statuses),finnhub(statuses),newsApi(statuses),gdelt(statuses),coin(statuses),macro(statuses),government(statuses)]); const markets=[...fh.markets,...av,...cg].filter((m,i,a)=>a.findIndex(x=>x.symbol===m.symbol)===i); const news=[...fh.news,...na].filter(x=>x.title&&x.url).slice(0,60); const events=[...gd,...news.slice(0,18).map(n=>{const [lat,lon]=locate(n.title); return {...n,lat,lon,summary:n.title,impact:`Potential ${n.category.toLowerCase()} impact across exposed assets.`};})]; const risks=risk(news,events); const insights={"Executive Brief":news.length?`Monitoring ${news.length} live headlines, ${markets.length} market instruments, and ${events.length} mapped events.`:"No live headlines returned yet. Add provider keys in Vercel or wait for APIs to respond.","Market Risk Summary":`${risks["Market Risk"]}% market stress score from live source categories.`,"Geopolitical Risk Summary":`${risks["Geopolitical Risk"]}% geopolitical score from GDELT/news severity.`,"Regulatory Risk Summary":`${risks["Regulatory Risk"]}% regulatory score from Federal Register, Congress, and SEC coverage.`,"What Changed":news[0]?.title||"No change detected because live feeds are unavailable.","What To Watch Next":"Watch high-severity headlines, SEC filing updates, rates data, energy events, and watchlist-linked news.","Confidence":"Confidence depends on configured provider coverage and successful API responses."}; return NextResponse.json({generatedAt:new Date().toISOString(),status:statuses,markets,news,events,macro:ma,filings:gov.filings,regulations:gov.regs,insights,risks}); }
