import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

type Severity = "INFO" | "WATCH" | "ALERT" | "CRITICAL";
type Instrument = { symbol: string; name: string; price: number | null; changePercent: number | null; source: string; status: string; group: "index" | "equity" | "sector" | "commodity" | "crypto" | "rates"; note?: string };
type NewsItem = { title: string; source: string; url: string; category: string; severity: Severity; publishedAt: string };
type EventItem = NewsItem & { lat: number; lon: number; summary: string; impact: string; layer: string; confidence?: number };
type QuoteDef = { symbol: string; name: string; group: Instrument["group"]; note?: string };
type LayerStat = { layer: string; count: number; severe: number; sources: string[] };

const marketUniverse: QuoteDef[] = [
  { symbol: "SPY", name: "S&P 500 ETF", group: "index" }, { symbol: "QQQ", name: "Nasdaq 100 ETF", group: "index" }, { symbol: "DIA", name: "Dow Industrials ETF", group: "index" }, { symbol: "IWM", name: "Russell 2000 ETF", group: "index" },
  { symbol: "TLT", name: "20Y Treasury ETF", group: "rates" }, { symbol: "IEF", name: "7-10Y Treasury ETF", group: "rates" }, { symbol: "UUP", name: "US Dollar Index ETF", group: "rates" }, { symbol: "FXE", name: "Euro ETF", group: "rates" }, { symbol: "FXY", name: "Yen ETF", group: "rates" },
  { symbol: "AAPL", name: "Apple", group: "equity" }, { symbol: "MSFT", name: "Microsoft", group: "equity" }, { symbol: "NVDA", name: "NVIDIA", group: "equity" }, { symbol: "AMZN", name: "Amazon", group: "equity" }, { symbol: "GOOGL", name: "Alphabet", group: "equity" }, { symbol: "META", name: "Meta", group: "equity" }, { symbol: "TSLA", name: "Tesla", group: "equity" }, { symbol: "JPM", name: "JPMorgan", group: "equity" }, { symbol: "BAC", name: "Bank of America", group: "equity" }, { symbol: "GS", name: "Goldman Sachs", group: "equity" }, { symbol: "XOM", name: "Exxon Mobil", group: "equity" }, { symbol: "CVX", name: "Chevron", group: "equity" }, { symbol: "TSM", name: "Taiwan Semiconductor", group: "equity" }, { symbol: "AMD", name: "AMD", group: "equity" }, { symbol: "PLTR", name: "Palantir", group: "equity" },
  { symbol: "GLD", name: "Gold ETF", group: "commodity", note: "commodity proxy" }, { symbol: "SLV", name: "Silver ETF", group: "commodity", note: "commodity proxy" }, { symbol: "USO", name: "US Oil Fund", group: "commodity", note: "energy proxy" }, { symbol: "UNG", name: "US Natural Gas Fund", group: "commodity", note: "energy proxy" }, { symbol: "DBA", name: "Agriculture Fund", group: "commodity", note: "agriculture proxy" }, { symbol: "CPER", name: "Copper ETF", group: "commodity", note: "materials proxy" }
];
const sectorUniverse: QuoteDef[] = ["XLK:Technology", "XLF:Financials", "XLE:Energy", "XLV:Health Care", "XLI:Industrials", "XLY:Consumer Discretionary", "XLP:Consumer Staples", "XLU:Utilities", "XLB:Materials", "XLRE:Real Estate", "SMH:Semiconductors", "ITA:Aerospace & Defense", "XRT:Retail", "KRE:Regional Banks"].map((row) => { const [symbol, name] = row.split(":"); return { symbol, name, group: "sector" as const }; });
const commoditySeries = [{ fn: "WTI", symbol: "WTI", name: "WTI Crude Oil" }, { fn: "BRENT", symbol: "BRENT", name: "Brent Crude Oil" }, { fn: "NATURAL_GAS", symbol: "NATGAS", name: "Natural Gas" }, { fn: "COPPER", symbol: "COPPER", name: "Copper" }, { fn: "WHEAT", symbol: "WHEAT", name: "Wheat" }, { fn: "CORN", symbol: "CORN", name: "Corn" }, { fn: "COTTON", symbol: "COTTON", name: "Cotton" }, { fn: "SUGAR", symbol: "SUGAR", name: "Sugar" }];
const cryptoIds = [["bitcoin", "BTC", "Bitcoin"], ["ethereum", "ETH", "Ethereum"], ["solana", "SOL", "Solana"], ["binancecoin", "BNB", "BNB"], ["ripple", "XRP", "XRP"], ["cardano", "ADA", "Cardano"], ["chainlink", "LINK", "Chainlink"], ["avalanche-2", "AVAX", "Avalanche"], ["dogecoin", "DOGE", "Dogecoin"], ["the-open-network", "TON", "Toncoin"]] as const;
const ciks = [["AAPL", "0000320193"], ["MSFT", "0000789019"], ["NVDA", "0001045810"], ["TSLA", "0001318605"], ["AMZN", "0001018724"], ["META", "0001326801"], ["GOOGL", "0001652044"], ["JPM", "0000019617"], ["XOM", "0000034088"], ["AMD", "0000002488"], ["PLTR", "0001321655"]] as const;
const coords: Record<string, [number, number]> = { us: [39, -98], america: [39, -98], "united states": [39, -98], europe: [50, 10], asia: [34, 100], middle: [29, 45], gulf: [26, 51], china: [35, 103], beijing: [39.9, 116.4], russia: [61, 90], moscow: [55.8, 37.6], ukraine: [49, 31], kyiv: [50.45, 30.52], israel: [31, 35], iran: [32, 53], tehran: [35.7, 51.4], taiwan: [24, 121], japan: [36, 138], korea: [36, 128], india: [22, 79], pakistan: [30, 69], brazil: [-10, -55], chile: [-30, -71], mexico: [23, -102], "red sea": [18, 39], hormuz: [26.6, 56.2], suez: [30.6, 32.3], panama: [9, -79.6], singapore: [1.35, 103.8], london: [51.5, -0.1], paris: [48.85, 2.35], frankfurt: [50.1, 8.7], global: [20, 0] };
const newsApiQueries = ["markets OR stocks OR earnings OR bonds OR inflation OR Federal Reserve", "geopolitics OR sanctions OR conflict OR military OR shipping OR supply chain", "energy OR oil OR gas OR OPEC OR LNG OR commodities", "regulation OR Congress OR SEC OR Federal Register OR antitrust OR banking", "real estate OR housing OR mortgage OR commercial property OR REIT", "technology OR AI OR semiconductor OR cybersecurity OR cloud OR datacenter", "internet outage OR cable cut OR cloud outage OR cyber attack OR ransomware"];
const weatherPoints = [
  ["US Gulf Energy", 29.76, -95.37], ["New York Financial Hub", 40.71, -74.01], ["London Markets", 51.51, -0.13], ["Frankfurt Banking", 50.11, 8.68], ["Suez Canal", 30.59, 32.27], ["Strait of Hormuz", 26.57, 56.25], ["Singapore Shipping", 1.35, 103.82], ["Taiwan Semiconductor Corridor", 24.15, 120.67], ["Tokyo Markets", 35.68, 139.76], ["Mumbai Markets", 19.08, 72.88], ["Sao Paulo Markets", -23.55, -46.63], ["Los Angeles Ports", 33.74, -118.26]
] as const;
const statusPages = [
  { name: "OpenAI", url: "https://status.openai.com/api/v2/summary.json", lat: 37.78, lon: -122.42 },
  { name: "GitHub", url: "https://www.githubstatus.com/api/v2/summary.json", lat: 37.78, lon: -122.39 },
  { name: "Cloudflare", url: "https://www.cloudflarestatus.com/api/v2/summary.json", lat: 37.79, lon: -122.40 },
  { name: "Vercel", url: "https://www.vercel-status.com/api/v2/summary.json", lat: 37.77, lon: -122.42 },
  { name: "Anthropic", url: "https://status.anthropic.com/api/v2/summary.json", lat: 37.78, lon: -122.42 }
] as const;

function key(name: string) { return process.env[name] || ""; }
function num(value: unknown): number | null { const n = Number(String(value ?? "").replace("%", "")); return Number.isFinite(n) ? n : null; }
function inst(def: QuoteDef, price: number | null, changePercent: number | null, source: string, status = "ok"): Instrument { return { ...def, price, changePercent, source, status }; }
async function getJson(url: string, init?: RequestInit) { const headers = { Accept: "application/json", "User-Agent": key("SEC_USER_AGENT") || "WorldMarketWatcher/1.0 contact@example.com", ...(init?.headers || {}) }; const r = await fetch(url, { ...init, headers, cache: "no-store" }); if (!r.ok) throw new Error(`${r.status} ${r.statusText}`); return r.json(); }
function severity(text: string): Severity { const t = text.toLowerCase(); if (/war|missile|attack|invasion|default|crisis|earthquake|explosion|bankruptcy|emergency|tornado warning|hurricane warning|extreme|catastrophic/.test(t)) return "CRITICAL"; if (/sanction|lawsuit|fraud|investigation|conflict|inflation|rate hike|oil spike|shortage|probe|recall|severe|outage|ground stop|evacuation/.test(t)) return "ALERT"; if (/earnings|policy|fed|oil|supply|regulation|filing|tariff|housing|jobs|guidance|watch|advisory|weather/.test(t)) return "WATCH"; return "INFO"; }
function category(text: string) { const t = text.toLowerCase(); if (/earthquake|wildfire|volcano|storm|flood|cyclone|hurricane|tornado|weather/.test(t)) return "Natural Disaster"; if (/aircraft|flight|aviation|opensky|military/.test(t)) return "Military"; if (/outage|status|cloudflare|github|openai|vercel|anthropic|internet|cable/.test(t)) return "Outage"; if (/cloud|datacenter|data center|ai|semiconductor|chip|software|cyber|technology/.test(t)) return "Technology"; if (/oil|gas|energy|opec|lng|crude/.test(t)) return "Energy"; if (/war|military|missile|conflict|attack/.test(t)) return "Conflict"; if (/congress|federal|regulation|law|sec |filing|rule/.test(t)) return "Government"; if (/home|housing|mortgage|real estate|reit/.test(t)) return "Real Estate"; if (/inflation|jobs|fed|rates|gdp|treasury|yield|imf|world bank/.test(t)) return "Economy"; if (/china|russia|iran|taiwan|israel|ukraine|nato|sanction/.test(t)) return "Geopolitics"; return "Markets"; }
function layerFromCategory(cat: string, text = "") { const t = `${cat} ${text}`.toLowerCase(); if (/earthquake|wildfire|volcano|storm|flood|natural/.test(t)) return "natural"; if (/weather|tornado|hurricane|warning|advisory/.test(t)) return "weather"; if (/outage|status|internet|cloudflare|github|openai|vercel|anthropic/.test(t)) return "outages"; if (/cloud|datacenter|data center/.test(t)) return "cloudRegions"; if (/semiconductor|ai|software|technology|startup/.test(t)) return "techEvents"; if (/aircraft|flight|military/.test(t)) return "military"; if (/sanction/.test(t)) return "sanctions"; if (/conflict|war|missile|attack/.test(t)) return "conflicts"; if (/shipping|suez|hormuz|panama|waterway|canal/.test(t)) return "waterways"; if (/economy|inflation|rates|fed|gdp/.test(t)) return "economic"; if (/government|regulation|sec filing/.test(t)) return "regulations"; if (/energy|oil|gas/.test(t)) return "energy"; return "hotspots"; }
function locate(text: string): [number, number] { const t = text.toLowerCase(); for (const [needle, value] of Object.entries(coords)) if (t.includes(needle)) return value; return coords.global; }
function uniqueRows<T extends { title: string; url: string }>(rows: T[]) { const seen = new Set<string>(); return rows.filter((row) => { const k = row.url || row.title; if (!k || seen.has(k)) return false; seen.add(k); return Boolean(row.title); }); }
function eventRow(input: { title: string; source: string; url: string; category?: string; severity?: Severity; publishedAt?: string | null; lat: number; lon: number; summary?: string; impact?: string; layer?: string; confidence?: number }): EventItem { const cat = input.category || category(input.title); return { title: input.title, source: input.source, url: input.url, category: cat, severity: input.severity || severity(`${input.title} ${input.summary || ""}`), publishedAt: input.publishedAt || new Date().toISOString(), lat: input.lat, lon: input.lon, summary: input.summary || input.title, impact: input.impact || `Potential ${cat.toLowerCase()} impact across exposed markets, infrastructure, supply chains, policy, and watchlist assets.`, layer: input.layer || layerFromCategory(cat, input.title), confidence: input.confidence ?? 60 }; }
function centroid(geometry: any): [number, number] | null { if (!geometry) return null; if (geometry.type === "Point" && Array.isArray(geometry.coordinates)) return [Number(geometry.coordinates[1]), Number(geometry.coordinates[0])]; const coords: number[][] = []; const walk = (value: any) => { if (!Array.isArray(value)) return; if (typeof value[0] === "number" && typeof value[1] === "number") coords.push(value as number[]); else value.forEach(walk); }; walk(geometry.coordinates); if (!coords.length) return null; const lon = coords.reduce((s, row) => s + Number(row[0]), 0) / coords.length; const lat = coords.reduce((s, row) => s + Number(row[1]), 0) / coords.length; return Number.isFinite(lat) && Number.isFinite(lon) ? [lat, lon] : null; }
function layerStats(events: EventItem[]): LayerStat[] { const rows = new Map<string, LayerStat>(); for (const event of events) { const layer = event.layer || "hotspots"; const row = rows.get(layer) || { layer, count: 0, severe: 0, sources: [] }; row.count += 1; if (event.severity === "ALERT" || event.severity === "CRITICAL") row.severe += 1; if (!row.sources.includes(event.source)) row.sources.push(event.source); rows.set(layer, row); } return Array.from(rows.values()).sort((a, b) => b.severe - a.severe || b.count - a.count); }
function weatherSeverity(windGust: number | null, precip: number | null, code: number | null): Severity { if ((windGust ?? 0) >= 90 || (precip ?? 0) >= 30 || [95, 96, 99].includes(code ?? -1)) return "CRITICAL"; if ((windGust ?? 0) >= 65 || (precip ?? 0) >= 12 || [80, 81, 82].includes(code ?? -1)) return "ALERT"; if ((windGust ?? 0) >= 45 || (precip ?? 0) >= 4 || [61, 63, 65, 71, 73, 75].includes(code ?? -1)) return "WATCH"; return "INFO"; }

async function finnhubQuotes(defs: QuoteDef[], statuses: Record<string, string>) { if (!key("FINNHUB_API_KEY")) { statuses.Finnhub = "missing_key"; return defs.map((d) => inst(d, null, null, "Finnhub", "missing_key")); } const results = await Promise.all(defs.map(async (d) => { try { const q = await getJson(`https://finnhub.io/api/v1/quote?symbol=${d.symbol}&token=${key("FINNHUB_API_KEY")}`); return inst(d, num(q.c), num(q.dp), "Finnhub"); } catch { return inst(d, null, null, "Finnhub", "error"); } })); statuses.Finnhub = results.some((r) => r.status === "ok") ? "ok" : "error"; return results; }
async function alphaCommodities(statuses: Record<string, string>) { if (!key("ALPHA_VANTAGE_API_KEY")) { statuses.AlphaVantageCommodities = "missing_key"; return [] as Instrument[]; } const direct = await Promise.all(commoditySeries.map(async (d) => { try { const j = await getJson(`https://www.alphavantage.co/query?function=${d.fn}&interval=monthly&apikey=${key("ALPHA_VANTAGE_API_KEY")}`); const rows = Array.isArray(j.data) ? j.data : []; const latest = num(rows[0]?.value); const prev = num(rows[1]?.value); const change = latest !== null && prev ? ((latest - prev) / prev) * 100 : null; return inst({ symbol: d.symbol, name: d.name, group: "commodity", note: "Alpha Vantage commodity series" }, latest, change, "Alpha Vantage"); } catch { return inst({ symbol: d.symbol, name: d.name, group: "commodity", note: "Alpha Vantage commodity series" }, null, null, "Alpha Vantage", "error"); } })); statuses.AlphaVantageCommodities = direct.some((d) => d.status === "ok") ? "ok" : "error"; return direct; }
async function crypto(statuses: Record<string, string>) { try { const ids = cryptoIds.map(([id]) => id).join(","); const j = await getJson(`https://api.coingecko.com/api/v3/simple/price?ids=${ids}&vs_currencies=usd&include_24hr_change=true${key("COINGECKO_API_KEY") ? `&x_cg_demo_api_key=${key("COINGECKO_API_KEY")}` : ""}`); statuses.CoinGecko = "ok"; return cryptoIds.map(([id, symbol, name]) => inst({ symbol, name, group: "crypto" }, num(j[id]?.usd), num(j[id]?.usd_24h_change), "CoinGecko")); } catch { statuses.CoinGecko = "error"; return cryptoIds.map(([, symbol, name]) => inst({ symbol, name, group: "crypto" }, null, null, "CoinGecko", "error")); } }

async function liveNews(statuses: Record<string, string>) {
  const out: NewsItem[] = [];
  if (key("FINNHUB_API_KEY")) { try { const n = await getJson(`https://finnhub.io/api/v1/news?category=general&token=${key("FINNHUB_API_KEY")}`); for (const x of (Array.isArray(n) ? n : []).slice(0, 42)) out.push({ title: x.headline, source: x.source || "Finnhub", url: x.url, category: category(`${x.headline} ${x.summary}`), severity: severity(`${x.headline} ${x.summary}`), publishedAt: new Date((x.datetime || 0) * 1000).toISOString() }); statuses.FinnhubNews = "ok"; } catch { statuses.FinnhubNews = "error"; } }
  if (key("NEWS_API_KEY")) { try { const payloads = await Promise.all(newsApiQueries.map(async (q) => getJson(`https://newsapi.org/v2/everything?q=${encodeURIComponent(q)}&language=en&sortBy=publishedAt&pageSize=20&apiKey=${key("NEWS_API_KEY")}`))); for (const j of payloads) for (const a of j.articles || []) out.push({ title: a.title, source: a.source?.name || "NewsAPI", url: a.url, category: category(`${a.title} ${a.description}`), severity: severity(`${a.title} ${a.description}`), publishedAt: a.publishedAt }); statuses.NewsAPI = "ok"; } catch { statuses.NewsAPI = "error"; } } else statuses.NewsAPI = "missing_key";
  if (key("WORLD_NEWS_API_KEY")) { try { const j = await getJson("https://api.worldnewsapi.com/search-news?text=markets%20economy%20geopolitics%20energy%20regulation%20housing%20technology%20conflict%20sanctions%20cloud%20outage&language=en&number=45&sort=publish-time&sort-direction=DESC", { headers: { "x-api-key": key("WORLD_NEWS_API_KEY") } }); for (const a of j.news || []) out.push({ title: a.title, source: a.source || a.news_site || "World News API", url: a.url, category: category(`${a.title} ${a.summary}`), severity: severity(`${a.title} ${a.summary}`), publishedAt: a.publish_date || a.published_at }); statuses.WorldNews = "ok"; } catch { statuses.WorldNews = "error"; } } else statuses.WorldNews = "missing_key";
  return uniqueRows(out).sort((a, b) => (Date.parse(b.publishedAt) || 0) - (Date.parse(a.publishedAt) || 0)).slice(0, 160);
}
async function gdelt(statuses: Record<string, string>) { const out: EventItem[] = []; try { const q = encodeURIComponent("geopolitics sanctions conflict energy infrastructure cyber supply chain"); const j = await getJson(`${process.env.GDELT_BASE_URL || "https://api.gdeltproject.org"}/api/v2/doc/doc?query=${q}&mode=ArtList&format=json&maxrecords=70&sort=HybridRel`); for (const a of j.articles || []) { const [lat, lon] = locate(`${a.title} ${a.sourceCountry} ${a.domain}`); out.push(eventRow({ title: a.title, source: a.domain || a.sourceCountry || "GDELT", url: a.url, publishedAt: a.seendate || new Date().toISOString(), lat, lon, summary: a.title, confidence: 58 })); } statuses.GDELT = "ok"; } catch { statuses.GDELT = "error"; } return uniqueRows(out).slice(0, 70); }
async function usgsEarthquakes(statuses: Record<string, string>) { const out: EventItem[] = []; try { const j = await getJson("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson"); for (const f of j.features || []) { const [lon, lat] = f.geometry?.coordinates || []; const mag = num(f.properties?.mag); out.push(eventRow({ title: f.properties?.title || `Magnitude ${mag ?? "unknown"} earthquake`, source: "USGS", url: f.properties?.url || "https://earthquake.usgs.gov/", category: "Natural Disaster", severity: (mag ?? 0) >= 7 ? "CRITICAL" : (mag ?? 0) >= 6 ? "ALERT" : "WATCH", publishedAt: f.properties?.time ? new Date(f.properties.time).toISOString() : null, lat: Number(lat), lon: Number(lon), summary: `${f.properties?.place || "Earthquake"}. Magnitude ${mag ?? "unknown"}.`, impact: "Potential regional infrastructure, insurance, commodity, logistics, and real estate impact.", layer: "natural", confidence: 88 })); } statuses.USGS = "ok"; } catch { statuses.USGS = "error"; } return out.filter((e) => Number.isFinite(e.lat) && Number.isFinite(e.lon)); }
async function nasaEonet(statuses: Record<string, string>) { const out: EventItem[] = []; try { const j = await getJson("https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=60&days=30"); for (const event of j.events || []) { const geo = Array.isArray(event.geometry) ? event.geometry[event.geometry.length - 1] : null; const point = centroid(geo); if (!point) continue; const [lat, lon] = point; const cat = event.categories?.[0]?.title || "Natural Disaster"; out.push(eventRow({ title: event.title, source: "NASA EONET", url: event.link || "https://eonet.gsfc.nasa.gov/", category: "Natural Disaster", severity: severity(`${event.title} ${cat}`), publishedAt: geo?.date || null, lat, lon, summary: `${cat}: ${event.description || event.title}`, impact: "Natural event with possible supply-chain, logistics, insurance, agriculture, energy, or infrastructure impact.", layer: "natural", confidence: 78 })); } statuses.NASAEONET = "ok"; } catch { statuses.NASAEONET = "error"; } return out; }
async function noaaAlerts(statuses: Record<string, string>) { const out: EventItem[] = []; try { const j = await getJson("https://api.weather.gov/alerts/active?status=actual&message_type=alert", { headers: { Accept: "application/geo+json", "User-Agent": "WorldMarketWatcher/1.0 contact@example.com" } }); for (const feature of (j.features || []).slice(0, 80)) { const point = centroid(feature.geometry) || locate(feature.properties?.areaDesc || "us"); const sev = String(feature.properties?.severity || "").toLowerCase(); out.push(eventRow({ title: feature.properties?.headline || feature.properties?.event || "Active NWS alert", source: "NOAA/NWS", url: feature.properties?.uri || feature.id || "https://api.weather.gov/alerts/active", category: "Natural Disaster", severity: sev === "extreme" ? "CRITICAL" : sev === "severe" ? "ALERT" : "WATCH", publishedAt: feature.properties?.effective || feature.properties?.sent || null, lat: point[0], lon: point[1], summary: feature.properties?.description || feature.properties?.event || "Active weather alert", impact: "Weather alert with possible regional infrastructure, travel, energy demand, logistics, insurance, and real estate impact.", layer: "weather", confidence: 82 })); } statuses.NOAAAlerts = "ok"; } catch { statuses.NOAAAlerts = "error"; } return out; }
async function openMeteoWeather(statuses: Record<string, string>) { const out: EventItem[] = []; try { const rows = await Promise.all(weatherPoints.map(async ([label, lat, lon]) => { const j = await getJson(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,wind_speed_10m,wind_gusts_10m,precipitation,weather_code&timezone=UTC`); const current = j.current || {}; const gust = num(current.wind_gusts_10m); const precip = num(current.precipitation); const sev = weatherSeverity(gust, precip, num(current.weather_code)); return eventRow({ title: `${label}: weather ${sev.toLowerCase()}`, source: "Open-Meteo", url: "https://open-meteo.com/", category: "Natural Disaster", severity: sev, publishedAt: current.time ? `${current.time}Z` : null, lat: Number(lat), lon: Number(lon), summary: `Temp ${current.temperature_2m ?? "N/A"}C, wind ${current.wind_speed_10m ?? "N/A"} km/h, gust ${gust ?? "N/A"} km/h, precipitation ${precip ?? "N/A"} mm.`, impact: "Weather conditions monitored for market hubs, ports, energy corridors, semiconductor corridors, and logistics chokepoints.", layer: "weather", confidence: 70 }); })); out.push(...rows); statuses.OpenMeteo = "ok"; } catch { statuses.OpenMeteo = "error"; } return out; }
async function reliefWebDisasters(statuses: Record<string, string>) { const out: EventItem[] = []; try { const j = await getJson("https://api.reliefweb.int/v1/disasters?appname=world-market-watcher&limit=30&preset=latest&profile=full"); for (const row of j.data || []) { const fields = row.fields || {}; const loc = fields.primary_country?.location || fields.country?.[0]?.location || {}; const lat = num(loc.lat) ?? locate(fields.country?.[0]?.name || "global")[0]; const lon = num(loc.lon) ?? locate(fields.country?.[0]?.name || "global")[1]; out.push(eventRow({ title: fields.name || "ReliefWeb disaster", source: "ReliefWeb", url: fields.url || "https://reliefweb.int/disasters", category: "Natural Disaster", severity: severity(fields.name || "disaster"), publishedAt: fields.date?.created || fields.date?.changed || null, lat, lon, summary: fields.description || fields.name || "ReliefWeb disaster row", impact: "Humanitarian/disaster signal with possible supply chain, commodity, insurance, migration, and sovereign-risk impact.", layer: "natural", confidence: 72 })); } statuses.ReliefWeb = "ok"; } catch { statuses.ReliefWeb = "error"; } return out; }
async function ucdpConflicts(statuses: Record<string, string>) { const out: EventItem[] = []; const base = process.env.UCDP_BASE_URL || "https://ucdpapi.pcr.uu.se/api/gedevents/24.1"; try { const j = await getJson(`${base}?pagesize=70`); const rows = Array.isArray(j) ? j : Array.isArray(j.Result) ? j.Result : Array.isArray(j.results) ? j.results : []; for (const row of rows) { const lat = num(row.latitude) ?? num(row.lat); const lon = num(row.longitude) ?? num(row.lon); if (lat == null || lon == null) continue; out.push(eventRow({ title: row.event_clarity ? `UCDP conflict event: ${row.country || row.location || "unknown"}` : row.source_headline || `Conflict event: ${row.country || "unknown"}`, source: "UCDP", url: "https://ucdp.uu.se/", category: "Conflict", severity: num(row.best) && Number(row.best) > 10 ? "CRITICAL" : "ALERT", publishedAt: row.date_start || row.date_end || null, lat, lon, summary: `${row.country || "Conflict event"} ${row.side_a || ""} ${row.side_b || ""}`.trim(), impact: "Conflict signal with possible defense, energy, shipping, sanctions, currency, and sovereign-risk impact.", layer: "conflicts", confidence: 80 })); } statuses.UCDP = "ok"; } catch { statuses.UCDP = "error"; } return out; }
async function openSkyStates(statuses: Record<string, string>) { const out: EventItem[] = []; try { const j = await getJson("https://opensky-network.org/api/states/all"); const rows = Array.isArray(j.states) ? j.states : []; for (const state of rows.slice(0, 250)) { const callsign = String(state[1] || "").trim(); const country = String(state[2] || "Unknown"); const lon = num(state[5]); const lat = num(state[6]); const velocity = num(state[9]); const onGround = Boolean(state[8]); if (lat == null || lon == null || onGround) continue; const watch = /(Ukraine|Russia|Iran|Israel|Syria|Iraq|Yemen|Taiwan)/i.test(country); out.push(eventRow({ title: `Aircraft ${callsign || state[0]} over ${country}`, source: "OpenSky", url: "https://opensky-network.org/", category: "Military", severity: watch ? "WATCH" : "INFO", publishedAt: state[4] ? new Date(Number(state[4]) * 1000).toISOString() : null, lat, lon, summary: `Origin country ${country}; velocity ${velocity ?? "N/A"} m/s.`, impact: "Live air-traffic signal for aerospace, defense, conflict monitoring, sanctions, and logistics context.", layer: "military", confidence: 52 })); if (out.length >= 90) break; } statuses.OpenSky = "ok"; } catch { statuses.OpenSky = "error"; } return out; }
async function statusPageEvents(statuses: Record<string, string>) { const out: EventItem[] = []; const results = await Promise.all(statusPages.map(async (page) => { try { const j = await getJson(page.url); const incidents = Array.isArray(j.incidents) ? j.incidents : []; const degraded = (Array.isArray(j.components) ? j.components : []).filter((c: any) => !/operational/i.test(String(c.status || ""))); const rows = [...incidents.slice(0, 5).map((i: any) => ({ title: `${page.name}: ${i.name}`, status: i.status, body: i.impact, url: i.shortlink || i.url || page.url, at: i.updated_at || i.created_at })), ...degraded.slice(0, 5).map((c: any) => ({ title: `${page.name}: ${c.name} ${c.status}`, status: c.status, body: c.description, url: page.url, at: c.updated_at || new Date().toISOString() }))]; statuses[`${page.name}Status`] = "ok"; return rows.map((row: any) => eventRow({ title: row.title, source: `${page.name} Status`, url: row.url, category: "Outage", severity: /major|critical|outage/i.test(`${row.status} ${row.body}`) ? "ALERT" : "WATCH", publishedAt: row.at, lat: page.lat, lon: page.lon, summary: row.body || row.status || row.title, impact: "Technology provider status signal affecting AI, developer, cloud, market-data, and automation workflows.", layer: "outages", confidence: 86 })); } catch { statuses[`${page.name}Status`] = "error"; return [] as EventItem[]; } })); results.forEach((rows) => out.push(...rows)); return out; }
async function macro(statuses: Record<string, string>) { const out: Record<string, string> = {}; const fred = [["DGS10", "US 10Y"], ["DGS2", "US 2Y"], ["FEDFUNDS", "Fed Funds"], ["UNRATE", "Unemployment"], ["CPIAUCSL", "CPI Index"], ["MORTGAGE30US", "30Y Mortgage"], ["DCOILWTICO", "WTI Daily"], ["DTWEXBGS", "Dollar Index"]] as const; if (key("FRED_API_KEY")) { const rows = await Promise.all(fred.map(async ([series, label]) => { try { const j = await getJson(`https://api.stlouisfed.org/fred/series/observations?series_id=${series}&api_key=${key("FRED_API_KEY")}&file_type=json&sort_order=desc&limit=1`); return [label, j.observations?.[0]?.value || "Unavailable"] as const; } catch { return [label, "Unavailable"] as const; } })); rows.forEach(([k, v]) => { out[k] = v; }); statuses.FRED = rows.some(([, v]) => v !== "Unavailable") ? "ok" : "error"; } else statuses.FRED = "missing_key"; statuses.BLS = key("BLS_API_KEY") ? "configured" : "missing_key"; try { const wb = await getJson(`${process.env.WORLD_BANK_BASE_URL || "https://api.worldbank.org/v2"}/country/US/indicator/NY.GDP.MKTP.CD?format=json&per_page=1`); out["World Bank US GDP"] = wb?.[1]?.[0]?.value ? Number(wb[1][0].value).toLocaleString() : "Unavailable"; statuses.WorldBank = "ok"; } catch { statuses.WorldBank = "error"; } try { const imf = await getJson(`${process.env.IMF_BASE_URL || "https://www.imf.org/external/datamapper/api"}/v1/NGDP_RPCH/USA/CHN/DEU/JPN?periods=2026`); out["IMF Growth"] = imf?.values ? "loaded" : "Unavailable"; statuses.IMF = "ok"; } catch { statuses.IMF = "error"; } return out; }
async function government(statuses: Record<string, string>) { const regs: NewsItem[] = []; const filings: NewsItem[] = []; try { const term = encodeURIComponent("financial market housing bank energy AI technology cybersecurity real estate sanctions semiconductor"); const j = await getJson(`${process.env.FEDERAL_REGISTER_BASE_URL || "https://www.federalregister.gov/api/v1"}/documents.json?conditions%5Bterm%5D=${term}&per_page=35&order=newest`); for (const d of j.results || []) regs.push({ title: d.title, source: "Federal Register", url: d.html_url, category: "Government", severity: severity(d.title), publishedAt: d.publication_date }); statuses.FederalRegister = "ok"; } catch { statuses.FederalRegister = "error"; } if (key("CONGRESS_API_KEY")) { try { const j = await getJson(`https://api.congress.gov/v3/bill?format=json&limit=35&sort=updateDate+desc&api_key=${key("CONGRESS_API_KEY")}`); for (const b of j.bills || []) regs.push({ title: b.title, source: "Congress.gov", url: b.url, category: "Government", severity: severity(b.title), publishedAt: b.updateDate }); statuses.Congress = "ok"; } catch { statuses.Congress = "error"; } } else statuses.Congress = "missing_key"; const ua = key("SEC_USER_AGENT") || "WorldMarketWatcher/1.0 contact@example.com"; const secRows = await Promise.all(ciks.map(async ([symbol, cik]) => { try { const j = await getJson(`https://data.sec.gov/submissions/CIK${cik}.json`, { headers: { "user-agent": ua } }); const recent = j.filings?.recent; const rows: NewsItem[] = []; for (let i = 0; i < Math.min(6, recent?.accessionNumber?.length || 0); i++) rows.push({ title: `${symbol} ${recent.form[i]} filing`, source: "SEC EDGAR", url: `https://www.sec.gov/Archives/edgar/data/${Number(cik)}/${String(recent.accessionNumber[i]).replace(/-/g, "")}/${recent.primaryDocument[i]}`, category: "SEC Filing", severity: ["8-K", "10-K", "10-Q", "S-1"].includes(recent.form[i]) ? "WATCH" : "INFO", publishedAt: recent.filingDate[i] }); return rows; } catch { return []; } })); filings.push(...secRows.flat()); statuses.SEC = filings.length ? "ok" : "error"; return { regs: uniqueRows(regs).slice(0, 60), filings }; }
function breadth(instruments: Instrument[]) { const live = instruments.filter((m) => m.changePercent !== null); const advancers = live.filter((m) => (m.changePercent || 0) > 0).length; const decliners = live.filter((m) => (m.changePercent || 0) < 0).length; const unchanged = Math.max(0, live.length - advancers - decliners); const averageChange = live.length ? live.reduce((s, m) => s + (m.changePercent || 0), 0) / live.length : null; const riskTone = averageChange === null ? "Unavailable" : averageChange > 0.35 ? "Risk On" : averageChange < -0.35 ? "Risk Off" : "Mixed"; return { advancers, decliners, unchanged, averageChange, riskTone, coverage: live.length }; }
function risk(newsRows: NewsItem[], eventRows: EventItem[], instruments: Instrument[]) { const all = [...newsRows, ...eventRows]; const score = (re: RegExp) => Math.min(100, Math.round(all.filter((x) => re.test(`${x.title} ${x.category} ${"layer" in x ? x.layer : ""}`.toLowerCase())).length * 5)); const marketMove = Math.min(25, Math.abs(breadth(instruments).averageChange || 0) * 8); return { "Market Risk": Math.min(100, Math.round(score(/market|earnings|stock|rate|fed|inflation/) + marketMove)), "Geopolitical Risk": score(/war|conflict|sanction|china|russia|iran|ukraine|israel|taiwan/), "Regulatory Risk": score(/law|regulation|congress|federal|sec|filing/), "Energy Risk": score(/oil|gas|energy|opec|lng|crude/), "Real Estate Risk": score(/housing|mortgage|real estate|reit|rates/), "Natural Hazard Risk": score(/natural|earthquake|wildfire|weather|storm|flood/), "Technology Outage Risk": score(/outage|cloud|internet|cyber|status|datacenter|technology/), "Military / Airspace Risk": score(/military|aircraft|opensky|missile/) }; }

export async function GET() {
  const statuses: Record<string, string> = { OpenAI: key("OPENAI_API_KEY") ? "configured" : "missing_key", Reddit: key("REDDIT_CLIENT_ID") ? "configured" : "missing_key", Binance: key("BINANCE_API_KEY") ? "configured" : "missing_key", Census: key("CENSUS_API_KEY") ? "configured" : "missing_key", ACLED: key("ACLED_API_KEY") ? "configured" : "missing_key", NASAFIRMS: key("NASA_FIRMS_API_KEY") ? "configured" : "missing_key", AISStream: key("AISSTREAM_API_KEY") ? "configured" : "missing_key" };
  const [marketQuotes, sectorQuotes, alphaCommodityRows, cryptoRows, newsRows, gdeltRows, usgsRows, eonetRows, noaaRows, meteoRows, reliefRows, ucdpRows, openSkyRows, statusRows, macroRows, gov] = await Promise.all([finnhubQuotes(marketUniverse, statuses), finnhubQuotes(sectorUniverse, statuses), alphaCommodities(statuses), crypto(statuses), liveNews(statuses), gdelt(statuses), usgsEarthquakes(statuses), nasaEonet(statuses), noaaAlerts(statuses), openMeteoWeather(statuses), reliefWebDisasters(statuses), ucdpConflicts(statuses), openSkyStates(statuses), statusPageEvents(statuses), macro(statuses), government(statuses)]);
  const commodityProxies = marketQuotes.filter((m) => m.group === "commodity");
  const commodityRows = alphaCommodityRows.some((r) => r.price !== null) ? [...alphaCommodityRows, ...commodityProxies] : commodityProxies;
  const markets = marketQuotes.filter((m) => m.group !== "commodity");
  const newsEvents = newsRows.slice(0, 45).map((n) => { const [lat, lon] = locate(n.title); return eventRow({ ...n, lat, lon, summary: n.title, impact: `Potential ${n.category.toLowerCase()} impact across watchlist, sector, commodity, infrastructure, and policy exposure.`, layer: layerFromCategory(n.category, n.title), confidence: 48 }); });
  const events = uniqueRows([...gdeltRows, ...usgsRows, ...eonetRows, ...noaaRows, ...meteoRows, ...reliefRows, ...ucdpRows, ...openSkyRows, ...statusRows, ...newsEvents]).slice(0, 260);
  const risks = risk(newsRows, events, [...markets, ...sectorQuotes, ...commodityRows, ...cryptoRows]);
  const br = breadth([...markets, ...sectorQuotes]);
  const sourcesUsed = Object.entries(statuses).filter(([, v]) => v === "ok" || v === "configured").map(([k]) => k);
  const layers = layerStats(events);
  const insights = { "Executive Brief": newsRows.length || events.length ? `Monitoring ${newsRows.length} live headlines, ${markets.length + sectorQuotes.length + commodityRows.length + cryptoRows.length} instruments, ${gov.filings.length} SEC filings, ${gov.regs.length} regulatory rows, ${events.length} mapped OSINT events, and ${layers.length} live map layers.` : "Live feeds are unavailable. Add provider keys in Vercel or wait for APIs to respond.", "Market Risk Summary": `${risks["Market Risk"]}% market score. Breadth: ${br.advancers} advancers, ${br.decliners} decliners, tone ${br.riskTone}.`, "Geopolitical Risk Summary": `${risks["Geopolitical Risk"]}% geopolitical score from GDELT/news/UCDP severity and mapped event density.`, "Infrastructure Risk Summary": `${risks["Technology Outage Risk"]}% technology/outage score and ${risks["Natural Hazard Risk"]}% natural hazard score from status pages, NOAA, USGS, NASA EONET, ReliefWeb, and Open-Meteo.`, "Regulatory Risk Summary": `${risks["Regulatory Risk"]}% regulatory score from Federal Register, Congress, and SEC coverage.`, "What Changed": [...events, ...newsRows].sort((a, b) => (Date.parse(b.publishedAt) || 0) - (Date.parse(a.publishedAt) || 0))[0]?.title || "No change detected because live feeds are unavailable.", "What To Watch Next": "Watch critical map layers, provider outages, SEC filing changes, Fed/rates data, energy corridors, weather/natural hazards, sanctions, and ticker-linked headlines.", "Confidence": sourcesUsed.length ? `Moderate: ${sourcesUsed.join(", ")} configured or returning data.` : "Low: no live providers returned usable data." };
  return NextResponse.json({ generatedAt: new Date().toISOString(), status: statuses, markets, sectors: sectorQuotes, commodities: commodityRows, crypto: cryptoRows, news: newsRows, events, layers, macro: macroRows, filings: gov.filings, regulations: gov.regs, breadth: br, insights, risks }, { headers: { "Cache-Control": "no-store" } });
}
